module.exports = (data) => ({
    id: data._id,
    name: data.name,
    type: data.type,
    preference: data.preference,
    mealsPerDay: data.mealsPerDay,
    restrictions: data.restrictions,
    preferredFoods: data.preferredFoods,
    excludedFoods: data.excludedFoods,
    createdAt: data.createdAt,
    updatedAt: data.updatedAt,
    days: (data.days || []).map((day) => ({
        id: day._id,
        name: day.name,
        description: day.description,
        dailyCaloricTarget: day.dailyCaloricTarget,
        dailyMacros: data.dailyMacros,
        meals: (day.meals|| []).map((meal) => ({
            id: meal.id,
            name: meal.name,
            description: meal.description,
            type: meal.type,
            kcal: meal.kcal,
            protein: meal.protein,
            carb: meal.carbs,
            fat: meal.fat,
            fibre: meal.fibre,
            salt: meal.salt,
        })),
    })),
});
